# Generated by Django 3.0.2 on 2020-08-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('city_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('attribute1', models.CharField(max_length=25)),
                ('attribute2', models.CharField(max_length=25)),
                ('franchise', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=50)),
                ('franchise', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('suit', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('pv', models.FloatField()),
                ('epv', models.FloatField()),
                ('s_epv', models.FloatField()),
                ('contract', models.IntegerField(blank=True, null=True)),
                ('t_option', models.IntegerField(blank=True, null=True)),
                ('p_option', models.IntegerField(blank=True, null=True)),
                ('renew', models.CharField(blank=True, max_length=10)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('franchise', models.CharField(blank=True, max_length=25, null=True)),
                ('lineup', models.CharField(blank=True, max_length=10, null=True)),
                ('trainer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('stadium_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stadium_seats', models.IntegerField(blank=True, null=True)),
                ('stadium_boxes', models.IntegerField(blank=True, null=True)),
                ('stadium_grade', models.IntegerField(blank=True, null=True)),
                ('stadium_max_grade', models.IntegerField(blank=True, null=True)),
                ('home_field_advantage', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.City')),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ppg', models.FloatField()),
                ('std', models.FloatField()),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improved_bathrooms', models.BooleanField(default=False)),
                ('improved_concessions', models.BooleanField(default=False)),
                ('jumbotron', models.BooleanField(default=False)),
                ('upscale_bar', models.BooleanField(default=False)),
                ('hall_of_fame', models.BooleanField(default=False)),
                ('improved_seating', models.BooleanField(default=False)),
                ('improved_sound', models.BooleanField(default=False)),
                ('party_deck', models.BooleanField(default=False)),
                ('wi_fi', models.BooleanField(default=False)),
                ('fan_night', models.BooleanField(default=False)),
                ('family_game', models.BooleanField(default=False)),
                ('door_prizes', models.BooleanField(default=False)),
                ('mvp_night', models.BooleanField(default=False)),
                ('parade_of_champions', models.BooleanField(default=False)),
                ('bribe_the_refs', models.BooleanField(default=False)),
                ('easy_runs', models.BooleanField(default=False)),
                ('fan_factor', models.BooleanField(default=False)),
                ('train_player', models.BooleanField(default=False)),
                ('farm_system', models.BooleanField(default=False)),
                ('fan_favourites', models.BooleanField(default=False)),
                ('gourmet_restaurant', models.BooleanField(default=False)),
                ('beer_garden', models.BooleanField(default=False)),
                ('naming_rights', models.BooleanField(default=False)),
                ('event_planning', models.BooleanField(default=False)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise')),
            ],
        ),
    ]
