# Generated by Django 3.0.2 on 2020-05-13 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bigleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('franchise', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='team',
        ),
        migrations.RemoveField(
            model_name='gm',
            name='team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.RemoveField(
            model_name='season',
            name='team',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='team',
        ),
        migrations.AddField(
            model_name='coach',
            name='franchise',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='gm',
            name='franchise',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='franchise',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='lineup',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stadium',
            name='city',
            field=models.ForeignKey(default='city', on_delete=django.db.models.deletion.CASCADE, to='bigleague.City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='stadium_name',
            field=models.CharField(default='stadium_name', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AddField(
            model_name='season',
            name='franchise',
            field=models.ForeignKey(default='franchise', on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='franchise',
            field=models.ForeignKey(default='franchise', on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
            preserve_default=False,
        ),
    ]
