# Generated by Django 3.0.2 on 2020-08-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='attribute_one',
            field=models.CharField(blank=True, choices=[('clutch', 'clutch'), ('fame', 'fame'), ('focus', 'focus'), ('guts', 'guts'), ('substitution', 'substitution'), ('teamwork', 'teamwork'), ('underdog', 'underdog'), ('wildcard', 'wildcard')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='attribute_two',
            field=models.CharField(blank=True, choices=[('facilitator', 'facilitator'), ('promoter', 'promoter'), ('recruiter', 'recruiter'), ('scouter', 'scouter'), ('suitor', 'suitor'), ('trainer', 'trainer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gm',
            name='trait',
            field=models.CharField(choices=[('facilitator', 'facilitator'), ('promoter', 'promoter'), ('recruiter', 'recruiter'), ('scouter', 'scouter'), ('suitor', 'suitor'), ('trainer', 'trainer')], default='facilitator', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='suit',
            field=models.CharField(choices=[('diamond', 'diamond'), ('spade', 'spade'), ('club', 'club'), ('heart', 'heart')], default='spade', max_length=10),
        ),
    ]
