# Generated by Django 3.0.2 on 2020-08-16 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improved_bathrooms', models.BooleanField(default=False)),
                ('improved_concessions', models.BooleanField(default=False)),
                ('jumbotron', models.BooleanField(default=False)),
                ('upscale_bar', models.BooleanField(default=False)),
                ('hall_of_fame', models.BooleanField(default=False)),
                ('improved_seating', models.BooleanField(default=False)),
                ('improved_sound', models.BooleanField(default=False)),
                ('party_deck', models.BooleanField(default=False)),
                ('wi_fi', models.BooleanField(default=False)),
                ('fan_night', models.BooleanField(default=False)),
                ('family_game', models.BooleanField(default=False)),
                ('door_prizes', models.BooleanField(default=False)),
                ('mvp_night', models.BooleanField(default=False)),
                ('parade_of_champions', models.BooleanField(default=False)),
                ('bribe_the_refs', models.BooleanField(default=False)),
                ('easy_runs', models.BooleanField(default=False)),
                ('fan_factor', models.BooleanField(default=False)),
                ('train_player', models.BooleanField(default=False)),
                ('farm_system', models.BooleanField(default=False)),
                ('fan_favourites', models.BooleanField(default=False)),
                ('gourmet_restaurant', models.BooleanField(default=False)),
                ('beer_garden', models.BooleanField(default=False)),
                ('naming_rights', models.BooleanField(default=False)),
                ('event_planning', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='attribute1',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='attribute2',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='gm',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='gm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='season',
            name='season',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='stadium_boxes',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='stadium_grade',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='stadium_max_grade',
        ),
        migrations.RemoveField(
            model_name='stadium',
            name='stadium_seats',
        ),
        migrations.AddField(
            model_name='coach',
            name='attribute_one',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='attribute_two',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='league',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
        migrations.AddField(
            model_name='season',
            name='bonuses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='championships',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='fan_base',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='fan_index',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='penalties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='revenue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stadium',
            name='boxes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stadium',
            name='grade',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='stadium',
            name='max_grade',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='stadium',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gm',
            name='trait',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='epv',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='lineup',
            field=models.CharField(blank=True, choices=[('starter', 'starter'), ('rotation', 'rotation'), ('bench', 'bench')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='pv',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='renew',
            field=models.CharField(blank=True, choices=[('no', 'no'), ('non-repeat', 'non-repeat'), ('repeat', 'repeat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='s_epv',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='suit',
            field=models.CharField(choices=[('diamond', 'diamond'), ('spade', 'spade'), ('club', 'club'), ('heart', 'heart')], max_length=10),
        ),
        migrations.AlterField(
            model_name='season',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
        migrations.AlterField(
            model_name='season',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='ppg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='std',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='season',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='home_field_advantage',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.AddField(
            model_name='roster',
            name='coach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.Coach'),
        ),
        migrations.AddField(
            model_name='roster',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
        migrations.AddField(
            model_name='roster',
            name='gm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.GM'),
        ),
        migrations.AddField(
            model_name='roster',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.Player'),
        ),
        migrations.AddField(
            model_name='season',
            name='actions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.Action'),
        ),
    ]
