# Generated by Django 3.0.2 on 2020-12-30 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='franchise',
            old_name='username',
            new_name='user',
        ),
    ]
