# Generated by Django 3.0.2 on 2020-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0002_auto_20200818_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='attribute_two',
            field=models.CharField(blank=True, choices=[('clutch', 'clutch'), ('fame', 'fame'), ('focus', 'focus'), ('guts', 'guts'), ('substitution', 'substitution'), ('teamwork', 'teamwork'), ('underdog', 'underdog'), ('wildcard', 'wildcard')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='lineup',
            field=models.CharField(choices=[('ST', 'starter'), ('RO', 'rotation'), ('BE', 'bench')], default='BE', max_length=2),
        ),
        migrations.AlterField(
            model_name='player',
            name='renew',
            field=models.CharField(blank=True, choices=[('1', 'no'), ('2', 'non-repeat'), ('3', 'repeat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='suit',
            field=models.CharField(choices=[('1', 'diamond'), ('2', 'spade'), ('3', 'club'), ('4', 'heart')], default='2', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('attribute_one', 'attribute_two')},
        ),
    ]
