# Generated by Django 3.0.2 on 2020-03-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0002_playergeneration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergeneration',
            name='p_option',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playergeneration',
            name='t_option',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
