# Generated by Django 3.0.2 on 2020-08-16 06:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0002_auto_20200816_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='franchise',
            field=models.OneToOneField(default='franchise', on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='train_player',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
