# Generated by Django 3.0.2 on 2020-06-23 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0002_auto_20200513_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stadium',
            name='home_field_advantage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('improved_bathrooms', models.BooleanField(default=False)),
                ('improved_concessions', models.BooleanField(default=False)),
                ('jumbotron', models.BooleanField(default=False)),
                ('upscale_bar', models.BooleanField(default=False)),
                ('hall_of_fame', models.BooleanField(default=False)),
                ('improved_seating', models.BooleanField(default=False)),
                ('improved_sound', models.BooleanField(default=False)),
                ('party_deck', models.BooleanField(default=False)),
                ('wi_fi', models.BooleanField(default=False)),
                ('fan_night', models.BooleanField(default=False)),
                ('family_game', models.BooleanField(default=False)),
                ('door_prizes', models.BooleanField(default=False)),
                ('mvp_night', models.BooleanField(default=False)),
                ('parade_of_champions', models.BooleanField(default=False)),
                ('bribe_the_refs', models.BooleanField(default=False)),
                ('easy_runs', models.BooleanField(default=False)),
                ('fan_factor', models.BooleanField(default=False)),
                ('train_player', models.BooleanField(default=False)),
                ('farm_system', models.BooleanField(default=False)),
                ('fan_favourites', models.BooleanField(default=False)),
                ('gourmet_restaurant', models.BooleanField(default=False)),
                ('beer_garden', models.BooleanField(default=False)),
                ('naming_rights', models.BooleanField(default=False)),
                ('event_planning', models.BooleanField(default=False)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise')),
            ],
        ),
    ]
