# Generated by Django 3.0.2 on 2020-08-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0003_auto_20200818_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='attribute_one',
            field=models.CharField(choices=[('teamwork', 'teamwork'), ('clutch', 'clutch'), ('fame', 'fame'), ('focus', 'focus'), ('guts', 'guts'), ('substitution', 'substitution'), ('underdog', 'underdog'), ('wildcard', 'wildcard')], default='teamwork', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coach',
            name='attribute_two',
            field=models.CharField(choices=[('teamwork', 'teamwork'), ('clutch', 'clutch'), ('fame', 'fame'), ('focus', 'focus'), ('guts', 'guts'), ('substitution', 'substitution'), ('underdog', 'underdog'), ('wildcard', 'wildcard')], default='teamwork', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gm',
            name='trait',
            field=models.CharField(choices=[('facilitator', 'facilitator'), ('promoter', 'promoter'), ('recruiter', 'recruiter'), ('scouter', 'scouter'), ('suitor', 'suitor'), ('trainer', 'trainer')], max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='lineup',
            field=models.CharField(choices=[('bench', 'bench'), ('rotation', 'rotation'), ('starter', 'starter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='renew',
            field=models.CharField(choices=[('no', 'no'), ('non-repeat', 'non-repeat'), ('repeat', 'repeat')], max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='suit',
            field=models.CharField(choices=[('diamond', 'diamond'), ('spade', 'spade'), ('club', 'club'), ('heart', 'heart')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together=set(),
        ),
    ]
