# Generated by Django 3.0.2 on 2020-08-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0003_auto_20200623_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='gm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gm',
            name='trait',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.IntegerField(),
        ),
    ]
