# Generated by Django 3.0.2 on 2020-04-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0003_auto_20200317_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playergeneration',
            name='grade',
        ),
    ]
