# Generated by Django 3.0.2 on 2020-08-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0004_auto_20200822_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lineup',
            field=models.CharField(choices=[('bench', 'bench'), ('rotation', 'rotation'), ('starter', 'starter')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='renew',
            field=models.CharField(choices=[('no', 'no'), ('non-repeat', 'non-repeat'), ('repeat', 'repeat')], max_length=10, null=True),
        ),
    ]
