# Generated by Django 3.0.2 on 2020-08-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0004_auto_20200806_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise', unique=True),
        ),
    ]
