# Generated by Django 3.0.2 on 2020-04-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0004_remove_playergeneration_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergeneration',
            name='grade',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
