# Generated by Django 3.0.2 on 2020-08-16 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0004_auto_20200816_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roster',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='gm',
        ),
        migrations.AlterField(
            model_name='roster',
            name='player',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.Player'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.Coach')),
                ('franchise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise')),
                ('gm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.GM')),
            ],
        ),
    ]
