# Generated by Django 3.0.2 on 2020-08-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0005_auto_20200830_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='lineup',
        ),
        migrations.AddField(
            model_name='roster',
            name='lineup',
            field=models.CharField(choices=[('bench', 'bench'), ('rotation', 'rotation'), ('starter', 'starter')], max_length=10, null=True),
        ),
    ]
