# Generated by Django 3.0.2 on 2020-08-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0005_auto_20200816_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='season',
            name='id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AlterField(
            model_name='action',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bigleague.Franchise'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player',
            field=models.OneToOneField(default='Diamond', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bigleague.Player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='season',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bigleague.Franchise'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bigleague.Franchise'),
        ),
    ]
