# Generated by Django 3.0.2 on 2020-08-08 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0005_auto_20200807_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
    ]
