# Generated by Django 3.0.2 on 2020-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0006_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='GM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gm', models.CharField(max_length=50)),
            ],
        ),
    ]
