# Generated by Django 3.0.2 on 2020-09-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0006_auto_20200830_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
        ),
    ]
