# Generated by Django 3.0.2 on 2020-09-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0007_player_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.ForeignKey(default='bigleague', on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
            preserve_default=False,
        ),
    ]
