# Generated by Django 3.0.2 on 2020-04-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0007_gm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.AddField(
            model_name='playergeneration',
            name='s_epv',
            field=models.FloatField(default=50),
            preserve_default=False,
        ),
    ]
