# Generated by Django 3.0.2 on 2020-05-01 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0008_auto_20200430_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('attribute1', models.CharField(max_length=25)),
                ('attribute2', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='GMs',
            fields=[
                ('trait', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('suit', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('pv', models.FloatField()),
                ('epv', models.FloatField()),
                ('s_epv', models.FloatField()),
                ('contract', models.IntegerField(blank=True, null=True)),
                ('t_option', models.IntegerField(blank=True, null=True)),
                ('p_option', models.IntegerField(blank=True, null=True)),
                ('renew', models.CharField(blank=True, max_length=10)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('grade', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stadium_seats', models.IntegerField(blank=True, null=True)),
                ('stadium_boxes', models.IntegerField(blank=True, null=True)),
                ('stadium_grade', models.IntegerField(blank=True, null=True)),
                ('stadium_max_grade', models.IntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Cities')),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='GM',
        ),
        migrations.DeleteModel(
            name='Playergeneration',
        ),
        migrations.AddField(
            model_name='players',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Teams'),
        ),
        migrations.AddField(
            model_name='gms',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Teams'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Teams'),
        ),
    ]
