# Generated by Django 3.0.2 on 2021-08-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0020_player_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='attribute_one',
            field=models.CharField(choices=[('teamwork', 'teamwork'), ('clutch', 'clutch'), ('fame', 'fame'), ('focus', 'focus'), ('guts', 'guts'), ('substitution', 'substitution'), ('underdog', 'underdog'), ('wildcard', 'wildcard'), ('road', 'road')], max_length=12),
        ),
        migrations.AlterField(
            model_name='coach',
            name='attribute_two',
            field=models.CharField(choices=[('teamwork', 'teamwork'), ('clutch', 'clutch'), ('fame', 'fame'), ('focus', 'focus'), ('guts', 'guts'), ('substitution', 'substitution'), ('underdog', 'underdog'), ('wildcard', 'wildcard'), ('road', 'road')], max_length=12),
        ),
    ]
