# Generated by Django 3.0.2 on 2021-08-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0021_auto_20210819_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='id',
        ),
        migrations.AlterField(
            model_name='action',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bigleague.Franchise'),
        ),
    ]
