# Generated by Django 3.0.2 on 2021-08-19 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0022_auto_20210819_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
    ]
