# Generated by Django 3.0.2 on 2021-11-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0030_auto_20211113_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='franchise',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='franchise',
            unique_together={('franchise', 'league')},
        ),
    ]
