FRANCHISE_NAMES = [
    "Aces", "All Stars", "Avengers", "Aztecs", "Big Blues", "Big Red", "Blazers", "Cyclones", "Devils", "Dragons",
    "Dream", "Dynamo", "Flames", "Flash", "Force", "Fury", "Golden Bears", "Groove", "Heatwave", "Hurricanes",
    "Icons", "Jam", "Legends", "Lightning", "Masters", "Mavericks", "Monarchy", "Pioneers", "Pride", "Racers",
    "Rebels", "Renegades", "Riptide", "Royals", "Soul", "Spartans", "Spirit", "Storm", "Strikers",
    "Trojans", "United", "Violets", "Voodoo", "Warriors", "Wild", "Zephyrs"
]

PLAYER_NAMES = [('Kris', 'Bryant'), ('Ken', 'Stabler'), ('Gina', 'Carano'), ('Joe', 'Carter'), ('David', 'Price'),
                ('Karim', 'Benzema'), ('Tony', 'Parker'), ('Tony', 'Stewart'), ('Paul', 'Molitor'), ('John', 'Terry'),
                ('Patrick', 'Mahomes'), ('Maurice', 'Greene'), ('Yvan', 'Cournoyer'), ('Ronaldo', ' '),
                ('Andy', 'Pettitte'), ('Sebastian', 'Coates'), ('Elvis', 'Andrus'), ('Gary', 'Kidd'),
                ('Rusty', 'Wallace'),
                ('Juan', 'Marichal'), ('Joe', 'Montana'), ('John', 'McEnroe'), ('José', 'Altuve'),
                ('Pedro', 'Rodríguez'),
                ('Kurt', 'Busch'), ('Robbie', 'Fowler'), ('Pele', ' '), ('Kobe', 'Bryant'), ('Lionel', 'Messi'),
                ('Elena', 'Dementieva'), ('Gary', 'Player'), ('James', 'Hunt'), ('Hank', 'Greenberg'),
                ('Miguel', 'Cabrera'), ('Coco', 'Gauff'), ('Vlade', 'Divac'), ('Cristiano', 'Ronaldo'),
                ('Bjorn', 'Borg'),
                ('Koji', 'Uehara'), ('Clyde', 'Drexler'), ('Joey', 'Chestnut'), ('Bill', 'Walton'), ('Sandy', 'Koufax'),
                ('Curt', 'Schilling'), ('Jean-Claude', 'Killy'), ('Mick', 'Doohan'), ('Serena', 'Williams'),
                ('Shawn', 'Kemp'), ('Dale', 'Earnhardt'), ('Larry', 'Bird'),
                ('Martina', 'Navratilova'), ('Dan', 'Marino'), ('Kieron', 'Pollard'), ('Toni', 'Kukoc'),
                ('Steve', 'Collins'), ('Juli', 'Inkster'), ('Deion', 'Sanders'), ('Julius', 'Erving'),
                ('Roy', 'Halladay'),
                ('George', 'Foreman'), ('Manny', 'Ramirez'), ('Ronnie', "O'Sullivan"),
                ('Mike', 'Schmidt'), ('LaDainian', 'Tomlinson'), ('Adrian', 'Beltre'), ('Chris', 'Froome'),
                ('Gary', 'Lineker'), ('Ricky', 'Williams'), ('Joe', 'Namath'), ('Alan', 'Shearer'), ('Muhammad', 'Ali'),
                ('Allyson', 'Felix'), ('Jack', 'Dempsey'), ('Ty', 'Cobb'), ('Marcel', 'Hirscher'),
                ('Jean-Pierre', 'Rives'), ('Dick', 'Vermeil'), ('Derek', 'Jeter'), ('Edwin', 'Moses'),
                ('Sergei', 'Bubka'),
                ('Paul', 'Pierce'), ('John', 'Havlicek'), ('Hank', 'Kins'), ('Shawn', 'Johnson'), ('Drew', 'Brees'),
                ('Wilfred', 'Benitez'), ('Tiger', 'Woods'), ('T.J.', 'Oshie'), ('Andre', 'Agassi'),
                ('Michael', 'Johnson'),
                ('Tony', 'Gonzalez'), ('Maria', 'Sharapova'),
                ('Giancarlo', 'Stanton'), ('Pedro', 'Martinez'), ('Harold', 'Carmichael'), ('Bryan', 'Trottier'),
                ('Roger', 'Bannister'), ('Manny', 'Pacquiao'), ('Todd', 'Fitchett'), ('Emmitt', 'Smith'),
                ('Alfredo', 'Di Stefano'), ('Ron', 'Turcotte'), ('Alex', 'Rodriguez'), ('Dusty', 'Baker'),
                ('David', 'Wright'), ('Michael', 'Jordan'), ('Sachin', 'Tendulkar'), ('Tracy', 'McGrady'),
                ('Cristobal', 'Huet'), ('Carmen', 'Basilio'), ('Robin', 'Van Persie'), ('Miroslav', 'Klose'),
                ('Ken', 'Norton'), ('Tony', 'Gwynn'), ('Petr', 'Cech'),
                ('Miguel', 'Indurain'), ('David', 'Pizarro'), ('Katie', 'Ledecky'), ('Jelena', 'Dokic'),
                ('Venus', 'Williams'), ('Trey', 'Hardee'), ('Maurice', 'Richard'), ('Terry', 'Bradshaw'),
                ('Janica', 'Kostelic'), ('Jim', 'Kelly'), ('Torii', 'Hunter'), ('David', 'Nabarro'),
                ('Jacques', 'Plante'),
                ('Billie', 'Jean King'), ('Wade', 'Boggs'), ('Lynn', 'Swann'), ('Zlatko', 'Kranjcar'),
                ('Bob', 'Beamon'),
                ('Tony', 'Sanchez'), ('Moses', 'Malone'), ('Mike', 'Bossy'), ('Tom', 'Daley'), ('Jerry', 'Kramer'),
                ('Torsten', 'Frings'), ('Bobby', 'Hull'), ('Dwyane', 'Wade'), ('Nolan', 'Ryan'), ('Mookie', 'Betts'),
                ('Adam', 'Foote'), ('Mats', 'Sundin'), ('Andy', 'Murray'), ('Ricky', 'Henderson'), ('David', 'Wells'),
                ('Brian', 'Boitano'), ('Floyd', 'Mayweather'), ('Mikhail', 'Kukushkin'),
                ('Pete', 'Rose'), ('Jerry', 'Rice'), ('Kevin', 'Durant'), ('Thurman', 'Thomas'),
                ('Steffi', 'Graf'),
                ('Bubba', 'Watson'), ('Albert', 'Pujols'), ('Teddy', 'Riner'), ('Ivan', 'Lendl'), ('Jim', 'Thorpe'),
                ('Jim', 'Abbott'), ('Ruth', 'Riley'), ('Adrian', 'Petersson'), ('Arnold', 'Palmer'), ('Sasha', 'Cohen'),
                ('Chris', 'Paul'), ('Carl', 'Lewis'), ('Hank', 'Aaron'), ('Vladimir', 'Konstantinov'),
                ('James', 'Harden'),
                ('Randy', 'Wittman'), ('Johnny', 'Cueto'), ('Kawhi', 'Leonard'), ('Dave', 'Parker'), ('Lamar', 'Jackson'),
                ('Michael', 'Oher'), ('Ron', 'Jaworski'), ('Michael', 'Phelps'), ('Steve', 'Davis'),
                ('Jason', 'Giambi'),
                ('Lionel', 'Rose'), ('Didier', 'Drogba'), ('Greg', 'Lemond'), ('Scott', 'Brosius'), ('Ian', 'Botham'),
                ('Caeleb', 'Dressel'), ('John', 'Daly'), ('Lance', 'Armstrong'), ('Wilma', 'Rudolph'),
                ('Wilfredo', 'Gómez'), ('Megan', 'Rapinoe'), ('Diego', 'Maradona'), ('Evander', 'Holyfield'),
                ('Jackie', 'Robinson'), ('Ronda', 'Rousey'), ('Frankie', 'Fraser'), ('Max', 'Holloway'),
                ('Mike', 'Powell'), ('Roberto', 'Duran'), ('Gary', 'Payton'), ('Pete', 'Sampras'), ('Larry', 'Holmes'),
                ('Gheorghe', 'Hagi'), ('Caster', 'Semenya'), ('Larry', 'Walker'), ('Sammy', 'Baugh'),
                ('Willie', 'Stargell'), ('James', 'Worthy'), ('Jack', 'Kemp'), ('Chris', 'Webber'),
                ('Ken', 'Griffey Jr.'),
                ('Novak', 'Djokovic'), ('Wayne', 'Rooney'), ('Thierry', 'Henry'), ('Jimmie', 'Johnson'),
                ('Jack', 'Nicklaus'), ('Penny', 'Taylor'), ('Emilio', 'Butragueño'), ('Sammy', 'Sosa'),
                ('Usain', 'Bolt'),
                ('Chris', 'Evert'), ('Seth', 'Jones'), ('Johnny', 'Sexton'), ('Wilt', 'Chamberlain'), ('Rui', 'Costa'),
                ('Rocky', 'Marciano'), ('Kenny', 'Smith'), ('Al', 'Davis'), ('Jens', 'Lehmann'), ('Marcus', 'Allen'),
                ('Mario', 'Andretti'), ('César', 'Cielo'), ('Carmen', 'Jorda'), ('Ray', 'Lewis'), ('Sidney', 'Crosby'),
                ('Frank', 'Robinson'), ('Paula', 'Radcliffe'), ('Mia', 'Hamm'), ('Lindsey', 'Vonn'), ('Gerd', 'Müller'),
                ('Zinedine', 'Zidane'), ('Jim', 'Rice'), ('Bobby', 'Orr'), ('Gareth', 'Bale'), ('Pele', 'Nascimento'),
                ('Andres', 'Iniesta'), ('Barry', 'Bonds'), ('Dale', 'Earnhardt Jr.'), ('Dick', 'Butkus'),
                ('Mickey', 'Mantle'), ('Rickey', 'Paulding'), ('Kareem', 'Abdul-Jabbar'), ('John', 'Elway'),
                ('Carl', 'Froch'), ('Eli', 'Manning'), ('Eric', 'Lindros'), ('Ronaldinho', 'Gaúcho'),
                ('Oscar', 'Robertson'), ('Lawrence', 'Taylor'), ('Víctor', 'Martínez'), ('Christine', 'Sinclair'),
                ('Randy', 'Johnson'), ('Nadia', 'Comaneci'), ('Tara', 'Lipinski'), ('Jim', 'Clark'),
                ('Gheorghe', 'Muresan'), ('Stacy', 'Lewis'), ('Lance', 'Mackey'), ('Jeff', 'Bagwell'),
                ('Edgar', 'Martinez'), ('Yohan', 'Blake'), ('Babe', 'Ruth'), ('Neymar', 'Jr.'),
                ('Joe', 'DiMaggio'), ('Mike', 'Tyson'), ('John', 'Amaechi'), ('Steve', 'Young'), ('Brian', 'Leetch'),
                ('Rory', 'McIlroy'), ('Zico', ' '), ('Bill', 'Russell'), ('Bobby', 'Bowden'), ('Sonny', 'Liston'),
                ('Chris', 'Hoy'), ('Brad', 'Lidge'), ('Bobby', 'Clarke'), ('Michael', 'Bevan'), ('Jean', 'Cruguet'),
                ('Steve', 'Redgrave'), ('Olga', 'Korbut'), ('Marcus', 'Camby'), ('Robert', 'Pires'), ('Jerry', 'West'),
                ('Tim', 'Duncan'), ('Adam', 'Oates'), ('Slobodan', 'Živojinović'), ('Wayne', 'Gretzky'),
                ('Jesse', 'Owens'), ('Ted', 'Williams'), ('Buster', 'Posey'), ('Alex', 'English'), ('J.J.', 'Watt'),
                ('Tom', 'Brady'), ('Guy', 'Lafleur'), ('Luka', 'Modric'), ('Darryl', 'Strawberry'), ('Mia', 'Farrow'),
                ('Rafael', 'Nadal'), ('Michael', 'Vick'), ('Johnny', 'Parker'), ('Peyton', 'Manning'), ('Yu-Na', 'Kim'),
                ('Sheryl', 'Swoopes'), ('Dennis', 'Eckersley'), ('Phil', 'Mickelson'), ('J.R.', 'Richard'),
                ('Steph', 'Curry'), ('Daniel', 'Nestor'), ('LeBron', 'James'), ('Lydia', 'Ko'), ('Larry', 'Johnson'),
                ('Simone', 'Biles'), ('Manu', 'Ginobili'), ('Tony', 'Hawk'), ('Roberto', 'Clemente'),
                ('Kylian', 'Mbappe'), ('Elgin', 'Baylor'), ('Carlos', 'Puyol'), ('George', 'Weah'),
                ('Manuel', "Neuer"), ('Bradley', 'Wiggins'), ('George', 'Best'), ('Franz', 'Beckenbauer'),
                ('Scottie', 'Pippen'), ('Alain', 'Prost'), ('Michael', 'Schumacher'), ('Johan', 'Cruyff'),
                ('Oliver', 'McCall'), ('Sylvester', 'Stallone'), ('Jim', 'Brown'), ('Roger', 'Federer'),
                ('Buster', 'Crabbe'), ('Magic', 'Johnson'), ('Diana', 'Taurasi'), ('Allen', 'Iverson'),
                ('Ray', 'Bourque'),
                ('Ron', 'Guidry'), ('Oswaldo', 'Oliva'), ('Carmelo', 'Anthony'), ('Shaquille', "O'Neal"),
                ('Xavi', 'Hernandez'), ('David', 'Beckham'), ('Marion', 'Jones'), ('Carl', 'Yastrzemski'),
                ('Scott', 'Hoch'), ('Caroline', 'Wozniacki'), ('Kristaps', 'Porzingis'), ('Honus', 'Wagner'),
                ('Carlos', 'Baerga'), ('George', 'Gervin'), ('Candace', 'Parker'), ('Marcelo', 'Rios'),
                ('Dwight', 'Gooden'), ('Jodie', 'Meeks'), ('Thomas', 'Heurtel'), ('Sonia', "O'Sullivan"),
                ('Lewis', 'Hamilton'), ('Tom', 'Seaver'), ('Chad', 'Ochocinco'), ('Billy', 'Casper'), ('Joe', 'Sakic'),
                ('Alfonso', 'Soriano'), ('Bob', 'Griese')]

COACH_NAMES = [('Phil', 'Jackson'), ('Vince', 'Lombardi'), ('Bill', 'Belichick'), ('Gregg', 'Popovich'),
               ('John', 'Wooden'), ('Red', 'Auerbach'), ('Pat', 'Riley'), ('Jose', 'Mourinho'), ('Bill', 'Walsh'),
               ('Bear', 'Bryant'), ('Don', 'Shula'), ('Mike', 'Krzyzewski'), ('Joe', 'Gibbs'), ('Bobby', 'Bowden'),
               ('Tom', 'Landry'), ('Dick', 'Vermeil'), ('Bill', 'Parcells'), ('Chuck', 'Noll'), ('Bill', 'Bowerman'),
               ('Scotty', 'Bowman'), ('Joachim', 'Löw'), ('Pep', 'Guardiola'), ('Bill', 'Self'), ('Casey', 'Stengel'),
               ('Alex', 'Ferguson')]
