FRANCHISE_NAMES = [
    "Aces", "All Stars", "Avengers", "Aztecs", "Big Blues", "Big Red", "Blazers", "Cyclones", "Devils", "Dragons",
    "Dream", "Dynamo", "Flames", "Flash", "Force", "Fury", "Golden Bears", "Groove", "Heatwave", "Hurricanes",
    "Icons", "Jam", "Legends", "Lightning", "Masters", "Mavericks", "Monarchy", "Pioneers", "Pride", "Racers",
    "Rebels", "Renegades", "Riptide", "Royals", "Soul", "Spartans", "Spirit", "Storm", "Strikers",
    "Trojans", "United", "Violets", "Voodoo", "Warriors", "Wild", "Zephyrs"
]

PLAYER_NAMES = sportsmen_and_women = [
    ('Muhammad', 'Ali'),
    ('Michael', 'Jordan'),
    ('Serena', 'Williams'),
    ('Usain', 'Bolt'),
    ('Pelé', None),
    ('Ronaldo', None),
    ('Diego', 'Maradona'),
    ('Alan', 'Shearer'),
    ('Bobby', 'Charlton'),
    ('Roger', 'Federer'),
    ('Tiger', 'Woods'),
    ('Babe', 'Ruth'),
    ('Michael', 'Phelps'),
    ('Wayne', 'Gretzky'),
    ('Carl', 'Lewis'),
    ('Lionel', 'Messi'),
    ('Cristiano', 'Ronaldo'),
    ('LeBron', 'James'),
    ('Jack', 'Nicklaus'),
    ('Martina', 'Navratilova'),
    ('Steffi', 'Graf'),
    ('Roger', 'Bannister'),
    ('Nadia', 'Comaneci'),
    ('Jesse', 'Owens'),
    ('Joe', 'Montana'),
    ('Magic', 'Johnson'),
    ('Michael', 'Schumacher'),
    ('Ayrton', 'Senna'),
    ('Jerry', 'Rice'),
    ('Kareem', 'Abdul-Jabbar'),
    ('Tom', 'Brady'),
    ('Zinedine', 'Zidane'),
    ('Bobby', 'Orr'),
    ('Sachin', 'Tendulkar'),
    ('Shane', 'Warne'),
    ('Anna', 'Meares'),
    ('Michael', 'Clarke'),
    ('Kelly', 'Slater'),
    ('Greg', 'LeMond'),
    ('Alain', 'Prost'),
    ('Michael', 'Johnson'),
    ('Johan', 'Cruyff'),
    ('Ronaldinho', None),
    ('Eddy', 'Merckx'),
    ('Valentino', 'Rossi'),
    ('Mike', 'Tyson'),
    ('Novak', 'Djokovic'),
    ('Kobe', 'Bryant'),
    ('Floyd', 'Mayweather Jr.'),
    ('Marta', None),
    ('Rafael', 'Nadal'),
    ('Kelly', 'Holmes'),
    ('Cathy', 'Freeman'),
    ('Dawn', 'Fraser'),
    ('Margaret', 'Court'),
    ('Mark', 'Spitz'),
    ('Chris', 'Hoy'),
    ('Bonnie', 'Blair'),
    ('Jackie', 'Joyner-Kersee'),
    ('Barry', 'Bonds'),
    ('Bjorn', 'Borg'),
    ('Evonne', 'Goolagong Cawley'),
    ('Rod', 'Laver'),
    ('Billie', 'Jean King'),
    ('Tony', 'Hawk'),
    ('Shaun', 'White'),
    ('Lindsey', 'Vonn'),
    ('Simone', 'Biles'),
    ('Neymar', 'Jr.'),
    ('Manny', 'Pacquiao'),
    ('Wayne', 'Rooney'),
    ('Yao', 'Ming'),
    ('Kenenisa', 'Bekele'),
    ('Mia', 'Hamm'),
    ('Annika', 'Sorenstam'),
    ('Maria', 'Sharapova'),
    ('Lewis', 'Hamilton'),
    ('Arnold', 'Palmer'),
    ('Pete', 'Sampras'),
    ('Andre', 'Agassi'),
    ('Tim', 'Duncan'),
    ('Karl', 'Malone'),
    ('Zlatan', 'Ibrahimovic'),
    ('Sue', 'Bird'),
    ('Venus', 'Williams'),
    ('Shaquille', 'O\'Neal'),
    ('Jim', 'Brown'),
    ('Gary', 'Player'),
    ('Ken', 'Griffey Jr.'),
    ('Jackie', 'Robinson'),
    ('Bill', 'Russell'),
    ('Deion', 'Sanders'),
    ('Hicham', 'El Guerrouj'),
    ('Allen', 'Iverson'),
    ('Katie', 'Ledecky'),
    ('Kim', 'Clijsters'),
    ('Lance', 'Armstrong'),
    ('Luka', 'Modric'),
    ('Andres', 'Iniesta'),
    ('Xavi', 'Hernandez'),
    ('Patrick', 'Mahomes'),
    ('Rob', 'Gronkowski'),
    ('Thierry', 'Henry'),
    ('Walter', 'Payton'),
    ('George', 'Best'),
    ('David', 'Beckham'),
]

COACH_NAMES = [('Phil', 'Jackson'), ('Vince', 'Lombardi'), ('Bill', 'Belichick'), ('Gregg', 'Popovich'),
               ('John', 'Wooden'), ('Red', 'Auerbach'), ('Pat', 'Riley'), ('Jose', 'Mourinho'), ('Bill', 'Walsh'),
               ('Bear', 'Bryant'), ('Don', 'Shula'), ('Mike', 'Krzyzewski'), ('Joe', 'Gibbs'), ('Bobby', 'Bowden'),
               ('Tom', 'Landry'), ('Dick', 'Vermeil'), ('Bill', 'Parcells'), ('Chuck', 'Noll'), ('Bill', 'Bowerman'),
               ('Scotty', 'Bowman'), ('Joachim', 'Löw'), ('Pep', 'Guardiola'), ('Bill', 'Self'), ('Casey', 'Stengel'),
               ('Alex', 'Ferguson')]
