# Generated by Django 3.0.2 on 2021-02-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coach',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='franchise',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gm',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roster',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stadium',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='franchise',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='gm',
            name='trait',
            field=models.CharField(choices=[('facilitator', 'facilitator'), ('promoter', 'promoter'), ('recruiter', 'recruiter'), ('scouter', 'scouter'), ('suitor', 'suitor'), ('trainer', 'trainer')], max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='league_name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='roster',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Player'),
        ),
        migrations.AlterField(
            model_name='season',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='stadium_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='franchise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
    ]
