# Generated by Django 3.0.2 on 2021-03-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0002_auto_20210205_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gm',
        ),
        migrations.RemoveField(
            model_name='league',
            name='franchise',
        ),
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.AddField(
            model_name='franchise',
            name='coach',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.Coach'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='gm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.GM'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
        ),
        migrations.AddField(
            model_name='player',
            name='franchise',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
        ),
        migrations.DeleteModel(
            name='Roster',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
