# Generated by Django 3.0.2 on 2021-03-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0003_auto_20210305_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='season',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
    ]
