# Generated by Django 3.0.2 on 2021-04-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0006_auto_20210426_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gm',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
            preserve_default=False,
        ),
    ]
