# Generated by Django 3.0.2 on 2021-04-28 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0007_auto_20210426_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='user',
            field=models.OneToOneField(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='league',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
            preserve_default=False,
        ),
    ]
