# Generated by Django 3.0.2 on 2021-05-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0009_remove_player_franchise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
        ),
    ]
