# Generated by Django 3.0.2 on 2021-05-03 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0010_auto_20210503_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.City'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='coach',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.Coach'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='gm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.GM'),
        ),
        migrations.AlterField(
            model_name='gm',
            name='trait',
            field=models.CharField(choices=[('facilitator', 'facilitator'), ('promoter', 'promoter'), ('recruiter', 'recruiter'), ('scouter', 'scouter'), ('suitor', 'suitor'), ('trainer', 'trainer')], max_length=12),
        ),
        migrations.AlterUniqueTogether(
            name='gm',
            unique_together={('trait', 'league')},
        ),
    ]
