# Generated by Django 3.0.2 on 2021-05-08 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0011_auto_20210503_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchise',
            name='city',
        ),
        migrations.AlterField(
            model_name='stadium',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bigleague.City'),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='franchise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
    ]
