# Generated by Django 3.0.2 on 2021-05-10 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0015_auto_20210508_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigleague.Franchise'),
        ),
    ]
