# Generated by Django 3.0.2 on 2021-05-10 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0017_auto_20210510_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roster',
        ),
    ]
