# Generated by Django 3.0.2 on 2021-08-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0023_auto_20210819_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
