# Generated by Django 3.0.2 on 2021-09-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0024_auto_20210819_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=50)),
                ('suit', models.CharField(choices=[('diamond', 'diamond'), ('spade', 'spade'), ('club', 'club'), ('heart', 'heart')], max_length=10)),
                ('age', models.IntegerField(default=20)),
                ('pv', models.FloatField(default=20)),
                ('epv', models.FloatField(default=20)),
                ('s_epv', models.FloatField(default=20)),
            ],
            options={
                'unique_together': {('season', 'name')},
            },
        ),
    ]
