# Generated by Django 3.0.2 on 2021-09-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0026_playerhistory_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='easy_runs_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='fan_factor_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='gourmet_restaurant_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='hall_of_fame_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='improved_bathrooms_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='improved_concessions_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='improved_seating_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='improved_sound_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='jumbotron_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='naming_rights_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='party_deck_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='upscale_bar_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='wi_fi_complete',
            field=models.BooleanField(default=False),
        ),
    ]
