# Generated by Django 3.0.2 on 2021-10-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0027_auto_20210918_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='box_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='boxes_sold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='ticket_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='season',
            name='tickets_sold',
            field=models.FloatField(default=0),
        ),
    ]
