# Generated by Django 3.0.2 on 2021-11-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0031_auto_20211113_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='stadium_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('name', 'league')},
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('name', 'league')},
        ),
    ]
