# Generated by Django 3.0.2 on 2021-04-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0008_auto_20210427_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='franchise',
        ),
    ]
