# Generated by Django 3.0.2 on 2021-05-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0016_auto_20210509_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='franchise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bigleague.Franchise'),
        ),
        migrations.AddField(
            model_name='player',
            name='lineup',
            field=models.CharField(choices=[('bench', 'bench'), ('rotation', 'rotation'), ('starter', 'starter')], max_length=10, null=True),
        ),
    ]
