# Generated by Django 3.0.2 on 2021-05-11 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0018_delete_roster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('franchise', 'season')},
        ),
    ]
