# Generated by Django 3.0.2 on 2021-09-03 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0025_playerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhistory',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bigleague.League'),
            preserve_default=False,
        ),
    ]
