# Generated by Django 3.0.2 on 2021-11-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigleague', '0029_auto_20211029_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city', 'league')},
        ),
    ]
